#!/usr/bin/env python
"""
Command-line utility to dump information about a pcap file.
"""

import sys
from pcapfile import savefile

def pcap_info(pcap_file):
    """
    Main function to read and display information about a libpcap
    savefile.
    """
    capfile = savefile.load_savefile(pcap_file, verbose=False)

    if capfile.valid:
        print capfile 
    else:
        print 'Invalid packet capture!'

if __name__ == '__main__':
    pcap_info(sys.argv[1])
